{
  imports = [
    ./alpaca.nix
    ./anki.nix
    ./archiver.nix
    ./element-desktop.nix
    ./gotify-desktop.nix
    ./gpg.nix
    ./keepassxc.nix
    ./koreader.nix
    ./libreoffice.nix
    ./localsend.nix
    ./lutris.nix
    ./nemo.nix
    ./nixpkgs-track.nix
    ./qalculate.nix
    ./qbittorrent.nix
    ./screenshot.nix
    ./syncthing.nix
    ./thunderbird.nix
    ./touchpad.nix
  ];
}
