{
  imports = [
    # ../values/meet.nix
    ../values/sci.nix
    ./authelia.nix
    ./bird-lg.nix
    ./caddy.nix
    ./dn42.nix
    ./ensure-path.nix
    ./flapalerted.nix
    ./fusion.nix
    ./gotify-fail2ban.nix
    ./gotify.nix
    ./karakeep.nix
    ./libretranslate.nix
    ./openlist.nix
    ./polaris.nix
    ./postgres.nix
    ./radicale.nix
    ./restic.nix
    ./rsshub.nix
    ./searxng.nix
    ./social.nix
    ./syncthing.nix
    ./tuwunel.nix
    ./umami.nix
    ./valkey.nix
    ./wakapi.nix
  ];
}
